/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ttt.h"

char **
currentboard_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static char * result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
play_1(argp, rqstp)
	play_args *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
checkwinner_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
