/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ttt.h"

bool_t
xdr_play_args(xdrs, objp)
	XDR *xdrs;
	play_args *objp;
{

	if (!xdr_int(xdrs, &objp->row))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->column))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->player))
		return (FALSE);
	return (TRUE);
}
